
const pinturas = [
    {
        id: 1,
        color: "Rosa Japon",
        tipo: "interior",
        img:"../resources/rosaJapon.png",
        litros:[1,4,10],
        "button text":["uno","cuatro","diez"],
        "button functions":[],
        precio: 11000,
        cantidad:0,
    },
    {
        id: 2,
        color: "Rosa Tierra",
        img:"../resources/rosaTierra.png",
        tipo: "interior",
        litros: 10,
        precio: 23500,
        cantidad:0,
    },
    {
        id: 3,
        color: "Gris Litoral",
        img:"../resources/grisLitoral.png",
        tipo: "interior",
        litros: 10,
        precio: 21200,
        cantidad:0,
    },
    {
        id: 4,
        color: "Gris Mesopotamia",
        tipo: "interior",
        img:"../resources/grisMesopotamia.png",
        litros: 4,
        precio: 19000,
        cantidad:0,
    },
    {
        id: 5,
        color: "Gris Norte",
        tipo: "exterior",
        img:"../resources/grisNorte.png",
        litros: 10,
        precio: 70000,
        cantidad:0,
    },
    {
        id: 6,
        color: "Gris Rio",
        tipo: "interior",
        img:"../resources/grisRio.png",
        litros: 4,
        precio: 19500,
        cantidad:0,
    },
    {
        id: 7,
        color: "Verde Celadon",
        img:"../resources/verdeCeladon.png",
        tipo: "interior",
        litros: 10,
        precio: 23000,
        cantidad:0,
    },
    {
        id: 8,
        color: "Azul Laguna",
        img:"../resources/azulLaguna.png",
        tipo: "interior",
        litros: 10,
        precio: 23000,
        cantidad:0,
    },
    {
        id: 9,
        color: "Azul Tormenta",
        img:"../resources/azulTormenta.png",
        tipo: "interior",
        litros: 10,
        precio: 23000,
        cantidad:0,
    },
]

document.addEventListener('DOMContentLoaded', pintarProductos(pinturas));