const latasPintura = [
    {
        id: 1,
        color: "rosa",
        tipo: "interior",
        img:"resources/1.webp",
        litros:[1,4,10],
        "button text":["uno","cuatro","diez"],
        "button functions":[],
        precio: 11000,
        cantidad:0,
    },
    {
        id: 2,
        color: "verde",
        img:"resources/2.webp",
        tipo: "exterior",
        litros: 10,
        precio: 23500,
        cantidad:0,
    },
    {
        id: 3,
        color: "blanco",
        img:"resources/3.jfif",
        tipo: "interior",
        litros: 10,
        precio: 21200,
        cantidad:0,
    },
    {
        id: 4,
        color: "rosa",
        tipo: "interior",
        img:"resources/4.jfif",
        litros: 4,
        precio: 19000,
        cantidad:0,
    },
    {
        id: 5,
        color: "blanco",
        tipo: "exterior",
        img:"resources/5.jfif",
        litros: 20,
        precio: 70000,
        cantidad:0,
    },
    {
        id: 6,
        color: "verde",
        tipo: "interior",
        img:"resources/6.jfif",
        litros: 4,
        precio: 19500,
        cantidad:0,
    },
    {
        id: 7,
        color: "naranja",
        img:"resources/7.jfif",
        tipo: "interior",
        litros: 10,
        precio: 23000,
        cantidad:0,
    },
]